"""Init

Revision ID: b7b09f2b9cc5
Revises: 
Create Date: 2024-11-05 17:17:05.666822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6d4bec815a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hw', sa.String(length=5), nullable=False),
    sa.Column('act', sa.String(length=5), nullable=False),
    sa.Column('tim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tem', sa.Float(), nullable=False),
    sa.Column('hum', sa.Float(), nullable=False),
    sa.Column('lig', sa.Float(), nullable=False),
    sa.Column('tim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('action')
    # ### end Alembic commands ###
